[package]
name = "ray-tracing-1"
version = "0.1.0"
edition = "2021"
authors = ["Tyson Liddell <tysonliddell@hotmail.com>"]
description = "Ray Tracing in One Weekend"

[dependencies]
env_logger = "0.10.0"
fastrand = "1.9.0"
log = "0.4.17"
