[package]
name = "ray-tracing-1"
version = "0.1.0"
edition = "2021"
authors = ["Tyson Liddell <tysonliddell@hotmail.com>"]
description = "Ray Tracing in One Weekend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
